before_script:
  - apk update
  - apk --no-cache add py3-pip python3 curl git
  - pip3 install pyyaml
  - curl -O https://raw.githubusercontent.com/FredHutch/swarm-build-helper/main/build_helper.py 
  # below is from https://stackoverflow.com/a/65810302/470769
  - mkdir -p $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  - set -x

stages:
  - build
  # TODO enable testing
  # - test
  - deploy

build:
  stage: build
  script:
    - rm -rf SEACR/
    - git clone https://github.com/FredHutch/SEACR.git
    - docker build -t sc-registry.fredhutch.org/seacr:test .
    - docker push sc-registry.fredhutch.org/seacr:test

# test:
#   stage: test
#   script:
#     - echo pass

deploy:
  stage: deploy
  only:
    refs:
        - master
  script:
    - docker tag sc-registry.fredhutch.org/seacr:test sc-registry.fredhutch.org/seacr:latest
    - docker push sc-registry.fredhutch.org/seacr:latest
    - sleep 15
    - echo $SC_SWARM_CICD_SSH_KEY | base64 -d > ./sc_swarm_cicd_ssh_key
    - chmod 0400 ./sc_swarm_cicd_ssh_key
    - cat docker-compose.yml | envsubst | python3 build_helper.py - | ssh -i ./sc_swarm_cicd_ssh_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@sc-swarm-mgr.fhcrc.org docker stack deploy --with-registry-auth -c - seacr
