# IMPORTANT: Version needs to be '2' for deployment but 
# seems to need to be '3.3' for local testing. TODO figure out why.
# In the meantime do not commit this file with version '3.3'.
version: '3.3'

services:

  rabbitmq:
    image: rabbitmq:3
    stdin_open: true
    ports:
      - "5672" # do we really need to expose this?
    labels:
      io.rancher.container.pull_image: always

  webapp:
    image: fredhutch/seacr # change to something in private registry?
    stdin_open: true
    ports:
      - "8001:8001"
    labels:
      io.rancher.container.pull_image: always
    volumes:
      - seacr-data:/seacr-data
    restart: always
    secrets:
    - SEACR_APP_SECRET
    environment:
      - SEACR_APP_SECRET

  celery:
    image: fredhutch/seacr # ??
    stdin_open: true
    command: ./run-celery.sh
    labels:
      io.rancher.container.pull_image: always
    volumes:
      - seacr-data:/seacr-data
    restart: always

  cron-cleaner:
    image: fredhutch/seacr
    stdin_open: true
    command: "cron && tail -f /var/log/cron.log"
    labels:
      io.rancher.container.pull_image: always
    volumes:
      - seacr-data:/seacr-data
    restart: always

secrets:
  SEACR_APP_SECRET:
    external: true

volumes:
  seacr-data:
    external: true
