version: '3.3'
networks:
  my-network:
    driver: bridge
services:

  rabbitmq:
    networks:
      - my-network
    image: rabbitmq:3
    stdin_open: true
    ports:
      - "5672" # do we really need to expose this?
    labels:
      io.rancher.container.pull_image: always

  webapp:
    networks:
      - my-network
    image: fredhutch/seacr # change to something in private registry?
    stdin_open: true
    ports:
      - "8001:8001"
    labels:
      io.rancher.container.pull_image: always
    volumes:
      - seacr-data:/jobs
    restart: always
    secrets:
    - SEACR_APP_SECRET
    environment:
      - SEACR_APP_SECRET

  celery:
    networks:
      - my-network
    image: fredhutch/seacr # ??
    stdin_open: true
    command: ./run-celery.sh
    labels:
      io.rancher.container.pull_image: always
    volumes:
      - seacr-data:/jobs
    restart: always

  cron-cleaner:
    networks:
      - my-network
    image: fredhutch/seacr
    stdin_open: true
    command: "cron && tail -f /var/log/cron.log"
    labels:
      io.rancher.container.pull_image: always
    volumes:
      - seacr-data:/jobs
    restart: always

secrets:
  SEACR_APP_SECRET:
    external: true

volumes:
  seacr-data:
    external: true

