version: '2'
services:
  rabbitmq:
    scale: 1
    start_on_create: true
  webapp:
    scale: 1
    start_on_create: true
  celery:
    scale: 1
    start_on_create: true
  cron-cleaner:
    scale: 1
    start_on_create: true